const { chromium } = require('playwright');
const path = require('path');
const fs = require('fs');

async function runQA() {
    const browser = await chromium.launch({ headless: true });
    const context = await browser.newContext();
    const page = await context.newPage();

    const report = {
        ac1: 'FAIL',
        ac2: 'FAIL',
        ac3: 'FAIL',
        ac4: 'FAIL',
        errors: []
    };

    try {
        // Determine the absolute path to the dashboard HTML file
        const dashboardPath = path.resolve(__dirname, '../../docs/dashboard.html');
        const fileUrl = `file://${dashboardPath}`;

        console.log(`Navigating to: ${fileUrl}`);
        await page.goto(fileUrl, { waitUntil: 'networkidle' });

        // --- AC1: Demo Data Rendering ---
        try {
            console.log('Testing AC1...');
            // Wait for the "Try with Demo Data" button and click it
            await page.waitForSelector('button:has-text("Try with Demo Data")', { timeout: 5000 });
            await page.click('button:has-text("Try with Demo Data")');

            // Give it a moment to render
            await page.waitForTimeout(1000);

            // Check if critical elements exist (indicating no white screen)
            const hasHeader = await page.isVisible('header.dashboard-header');
            const hasGrid = await page.isVisible('.dashboard-grid');

            if (hasHeader && hasGrid) {
                report.ac1 = 'PASS';
                console.log('AC1: PASS - Demo data rendered without crashing');
            } else {
                report.errors.push('AC1: Critical dashboard elements not visible after clicking Demo Data');
            }
        } catch (e) {
            report.errors.push(`AC1 Error: ${e.message}`);
        }

        // --- AC2: Directives Trello Board ---
        try {
            console.log('Testing AC2...');
            // Click Directives tab
            await page.click('.nav-tabs .tab-btn[data-target="directives"]');
            await page.waitForTimeout(500); // Wait for transition

            // Check for 3 columns
            const cols = await page.$$('.kanban-board .kanban-col');
            if (cols.length >= 3) {
                // Check for cards
                const pendingCards = await page.$$('.kanban-col.pending .directive-card');
                const activeCards = await page.$$('.kanban-col.active .directive-card');
                const doneCards = await page.$$('.kanban-col.done .directive-card');

                if (pendingCards.length > 0 || activeCards.length > 0 || doneCards.length > 0) {
                    report.ac2 = 'PASS';
                    console.log('AC2: PASS - Directives Trello board rendered with 3 columns and cards');
                } else {
                    report.errors.push('AC2: Kanban columns found but no cards rendered');
                }
            } else {
                report.errors.push(`AC2: Expected 3 kanban columns, found ${cols.length}`);
            }
        } catch (e) {
            report.errors.push(`AC2 Error: ${e.message}`);
        }

        // --- AC3: Context Pressure Gauge ---
        try {
            console.log('Testing AC3...');
            // Click Health tab
            await page.click('.nav-tabs .tab-btn[data-target="health"]');
            await page.waitForTimeout(500);

            const gaugeVisible = await page.isVisible('.health-gauge-container');
            const gaugeValue = await page.isVisible('.gauge-value');

            if (gaugeVisible && gaugeValue) {
                // Check if role lines are shown
                const roleLines = await page.textContent('.gauge-details');
                if (roleLines && roleLines.includes('lines')) {
                    report.ac3 = 'PASS';
                    console.log('AC3: PASS - Context Pressure gauge and role lines rendered');
                } else {
                    report.errors.push('AC3: Gauge rendered but role lines details missing');
                }
            } else {
                report.errors.push('AC3: Context Pressure gauge not visible');
            }
        } catch (e) {
            report.errors.push(`AC3 Error: ${e.message}`);
        }

        // --- AC4: Agent Topology DAG ---
        try {
            console.log('Testing AC4...');
            // Click Topology tab
            await page.click('.nav-tabs .tab-btn[data-target="topology"]');

            // Wait up to 3 seconds for Mermaid to render (it's async)
            console.log('Waiting for Mermaid rendering...');
            await page.waitForTimeout(2500);

            // Check if SVG was generated by Mermaid
            const svgExists = await page.isVisible('.topology-wrapper svg');

            if (svgExists) {
                report.ac4 = 'PASS';
                console.log('AC4: PASS - Agent Topology DAG rendered via Mermaid');
            } else {
                report.errors.push('AC4: Mermaid SVG not found after waiting');
            }
        } catch (e) {
            report.errors.push(`AC4 Error: ${e.message}`);
        }

        // Save screenshots for manual verification
        await page.goto(fileUrl);
        await page.click('button:has-text("Try with Demo Data")');
        await page.waitForTimeout(500);

        // Overview tab
        await page.click('.nav-tabs .tab-btn[data-target="overview"]');
        await page.waitForTimeout(500);
        await page.screenshot({ path: '/tmp/dashboard-overview.png' });

        // Directives tab
        await page.click('.nav-tabs .tab-btn[data-target="directives"]');
        await page.waitForTimeout(500);
        await page.screenshot({ path: '/tmp/dashboard-directives.png' });

        // Health tab
        await page.click('.nav-tabs .tab-btn[data-target="health"]');
        await page.waitForTimeout(500);
        await page.screenshot({ path: '/tmp/dashboard-health.png' });

        // Topology tab
        await page.click('.nav-tabs .tab-btn[data-target="topology"]');
        await page.waitForTimeout(2500);
        await page.screenshot({ path: '/tmp/dashboard-topology.png' });

        console.log('\n--- FINAL QA REPORT ---');
        console.log(JSON.stringify(report, null, 2));

    } catch (error) {
        console.error('Fatal Test Error:', error);
    } finally {
        await browser.close();
    }
}

runQA();
