const { chromium } = require('playwright');
const path = require('path');
const fs = require('fs');

async function runQA() {
    const browser = await chromium.launch({ headless: true });
    const context = await browser.newContext();
    const page = await context.newPage();

    const report = {
        ac1: 'FAIL',
        ac2: 'FAIL',
        ac3: 'FAIL',
        ac4: 'FAIL',
        errors: []
    };

    try {
        // Determine the absolute path to the dashboard HTML file
        const dashboardPath = path.resolve(__dirname, '../docs/dashboard.html');
        const fileUrl = `file://${dashboardPath}`;

        console.log(`Navigating to: ${fileUrl}`);
        await page.goto(fileUrl, { waitUntil: 'networkidle' });

        // --- AC1: Demo Data Rendering ---
        try {
            console.log('Testing AC1...');
            // Wait for the "Try with Demo Data" button and click it
            await page.waitForSelector('button:has-text("Try with Demo Data")', { timeout: 5000 });
            await page.click('button:has-text("Try with Demo Data")');

            // Give it a moment to render
            await page.waitForTimeout(1000);

            // Check if critical elements exist (indicating no white screen)
            const hasGrid = await page.isVisible('.stats-grid');

            if (hasGrid) {
                report.ac1 = 'PASS';
                console.log('AC1: PASS - Demo data rendered without crashing');
            } else {
                report.errors.push('AC1: Critical dashboard elements not visible after clicking Demo Data');
            }
        } catch (e) {
            report.errors.push(`AC1 Error: ${e.message}`);
        }

        // --- AC2: Directives Trello Board ---
        try {
            console.log('Testing AC2...');
            // Click Directives tab
            await page.click('.tab[data-tab="directives"]');
            await page.waitForTimeout(500); // Wait for transition

            // Check for 3 columns
            const cols = await page.$$('.kanban-board .kanban-col');
            if (cols.length >= 3) {
                // Check for cards
                const pendingCards = await page.$$('.kanban-col .directive-pending');
                const activeCards = await page.$$('.kanban-col .directive-active');
                const doneCards = await page.$$('.kanban-col .directive-done');

                // Due to specific class names in the generated HTML we just check for directive-item
                const cards = await page.$$('.directive-item');

                if (cards.length > 0) {
                    report.ac2 = 'PASS';
                    console.log('AC2: PASS - Directives Trello board rendered with 3 columns and cards');
                } else {
                    report.errors.push('AC2: Kanban columns found but no cards rendered');
                }
            } else {
                report.errors.push(`AC2: Expected 3 kanban columns, found ${cols.length}`);
            }
        } catch (e) {
            report.errors.push(`AC2 Error: ${e.message}`);
        }

        // --- AC3: Context Pressure Gauge ---
        try {
            console.log('Testing AC3...');
            // Click Health tab
            await page.click('.tab[data-tab="health"]');
            await page.waitForTimeout(500);

            const gaugeVisible = await page.isVisible('.gauge-container');
            const gaugeValue = await page.isVisible('.gauge-value');

            if (gaugeVisible && gaugeValue) {
                // Check if role lines are shown
                const roleLines = await page.textContent('.gauge-container');
                if (roleLines && roleLines.includes('Lines') || roleLines.includes('lines') || roleLines.includes('Risk')) {
                    report.ac3 = 'PASS';
                    console.log('AC3: PASS - Context Pressure gauge and role lines rendered');
                } else {
                    report.errors.push('AC3: Gauge rendered but risk details missing');
                }
            } else {
                report.errors.push('AC3: Context Pressure gauge not visible');
            }
        } catch (e) {
            report.errors.push(`AC3 Error: ${e.message}`);
        }

        // --- AC4: Agent Topology DAG ---
        try {
            console.log('Testing AC4...');
            // Click Topology tab
            await page.click('.tab[data-tab="topology"]');

            // Wait up to 3 seconds for Mermaid to render (it's async)
            console.log('Waiting for Mermaid rendering...');
            await page.waitForTimeout(2500);

            // Check if SVG was generated by Mermaid
            const svgExists = await page.isVisible('#topology-container svg');

            if (svgExists) {
                report.ac4 = 'PASS';
                console.log('AC4: PASS - Agent Topology DAG rendered via Mermaid');
            } else {
                report.errors.push('AC4: Mermaid SVG not found after waiting');
            }
        } catch (e) {
            report.errors.push(`AC4 Error: ${e.message}`);
        }

        console.log('\n--- FINAL QA REPORT ---');
        console.log(JSON.stringify(report, null, 2));

    } catch (error) {
        console.error('Fatal Test Error:', error);
    } finally {
        await browser.close();
    }
}

runQA();
