#!/bin/bash
# MUSE — .cursorrules Generator
# Generates a combined .cursorrules file from CLAUDE.md + core skills
# For legacy Cursor compatibility (pre-.cursor/rules/ era)
#
# Usage:
#   ./scripts/generate-cursorrules.sh [project-dir]
#
# The modern approach is `install.sh --tool cursor` which generates
# individual .mdc files in .cursor/rules/. This script is for users
# who prefer or need the old single-file .cursorrules format.

set -e

# ─── Colors ───
RED='\033[0;31m'
GREEN='\033[0;32m'
DIM='\033[2m'
RESET='\033[0m'

info()  { echo -e "  ${GREEN}✓${RESET} $1"; }
warn()  { echo -e "  ${RED}⚠${RESET} $1"; }

# ─── Args ───
TARGET_DIR="${1:-.}"
TARGET_DIR=$(cd "$TARGET_DIR" 2>/dev/null && pwd || echo "$TARGET_DIR")
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

OUTPUT_FILE="$TARGET_DIR/.cursorrules"

echo ""
echo "🎭 MUSE — .cursorrules Generator"
echo "═══════════════════════════════════"
echo ""

# ─── Find CLAUDE.md ───
CLAUDE_FILE=""
if [ -f "$TARGET_DIR/CLAUDE.md" ]; then
  CLAUDE_FILE="$TARGET_DIR/CLAUDE.md"
elif [ -f "$SCRIPT_DIR/templates/CLAUDE.md" ]; then
  CLAUDE_FILE="$SCRIPT_DIR/templates/CLAUDE.md"
else
  warn "No CLAUDE.md found in $TARGET_DIR or templates/"
  exit 1
fi

info "Source: $CLAUDE_FILE"

# ─── Build .cursorrules ───
{
  echo "# MUSE — AI Assistant Rules"
  echo "# Auto-generated by MUSE generate-cursorrules.sh"
  echo "# Source: CLAUDE.md + Core Skills"
  echo "# Regenerate with: ./scripts/generate-cursorrules.sh"
  echo ""
  echo "---"
  echo ""

  # Include CLAUDE.md content
  echo "## Constitution"
  echo ""
  cat "$CLAUDE_FILE"
  echo ""

  # Include core skills
  if [ -d "$SCRIPT_DIR/skills/core" ]; then
    echo "---"
    echo ""
    echo "## Core Skills"
    echo ""
    for skill_dir in "$SCRIPT_DIR/skills/core"/*/; do
      skill_file="$skill_dir/SKILL.md"
      [ ! -f "$skill_file" ] && continue
      skill_name=$(basename "$skill_dir")
      echo "### $skill_name"
      echo ""
      # Strip YAML frontmatter
      sed '1{/^---$/!q;};1,/^---$/d' "$skill_file"
      echo ""
    done
  fi

  # Include USER.md if exists
  if [ -f "$TARGET_DIR/USER.md" ]; then
    echo "---"
    echo ""
    echo "## User Preferences"
    echo ""
    cat "$TARGET_DIR/USER.md"
    echo ""
  fi

} > "$OUTPUT_FILE"

# ─── Summary ───
LINE_COUNT=$(wc -l < "$OUTPUT_FILE" | tr -d ' ')
info "Generated: $OUTPUT_FILE ($LINE_COUNT lines)"
echo ""
echo "  ${DIM}Note: For the modern multi-file format, use:${RESET}"
echo "  ${DIM}  ./scripts/install.sh --tool cursor --target $TARGET_DIR${RESET}"
echo ""
